services:
    Gally\Catalog\Filter\LocalizedCatalogLocaleFilter:
        arguments: [ '@doctrine', ~, '@?logger' ]
        tags: [ 'api_platform.filter' ]

    Gally\Catalog\Repository\CatalogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service } 

    Gally\Catalog\Repository\LocalizedCatalogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
            
    Gally\Catalog\State\LocalizedCatalogProcessor:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '@api_platform.doctrine.orm.state.persist_processor'
            - '@api_platform.doctrine.orm.state.remove_processor'
        tags:
            - { name: api_platform.state_processor }
                
    Gally\Catalog\Service\DefaultCatalogProvider:
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'

    Gally\Catalog\State\Source\LocalizedCatalogGroupOptionProvider:
        arguments:
            - '@Gally\Catalog\Repository\CatalogRepository'
            - '@api_platform.iri_converter'
        tags:
            - { name: api_platform.state_provider }
