services: 
    Gally\GraphQl\Decoration\Resolver\Stage\ReadStage:
        decorates: api_platform.graphql.state_provider.read
        arguments:
            - '@.inner'

    Gally\GraphQl\Decoration\Serializer\SerializerContextBuilder:
        decorates: api_platform.graphql.serializer.context_builder
        arguments:
            - '%api_platform.graphql.nesting_separator%'
            - '@.inner'

    Gally\GraphQl\Decoration\Type\RenameGraphQlQuery:
        decorates: api_platform.graphql.fields_builder
        arguments:
            - '@Gally\Configuration\State\ConfigurationProvider'
            - '@.inner'
                
    Gally\GraphQl\Error\ErrorHandler:
        decorates: api_platform.graphql.error_handler
        arguments:
            - '@logger'
            - '@.inner'
