services:

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\NumericAggregationConfigResolver:
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\DateAggregationConfigResolver:
        arguments:
            - '@Gally\Configuration\State\ConfigurationProvider'
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\SelectAggregationConfigResolver:
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\CategoryAggregationConfigResolver:
        arguments:
            - '@Gally\Search\Service\SearchContext'
            - '@Gally\Category\Repository\CategoryRepository'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\PriceAggregationConfigResolver:
        arguments:
            - '@Gally\Search\Service\SearchContext'
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\StockAggregationConfigResolver:
        tags:
            - { name: 'gally.search.aggregation.resolver' }

    Gally\Search\Elasticsearch\Request\Aggregation\ConfigResolver\GeoDistanceAggregationConfigResolver:
        arguments:
            - '@Gally\Search\Service\SearchContext'
            - '@Gally\Configuration\State\ConfigurationProvider'
        tags:
            - { name: 'gally.search.aggregation.resolver' }
