services:
    Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory:
        public: false
        arguments:
            $indexSettings: '@Gally\Index\Service\IndexSettings'
            $metadataManager: '@Gally\Index\Service\MetadataManager'
            $relevanceConfigurationFactory: '@Gally\Search\Elasticsearch\Request\Container\RelevanceConfiguration\RelevanceConfigurationFactory'
            $aggregationProvider: '@Gally\Search\Elasticsearch\Request\Aggregation\Provider\FilterableSourceFields'
            $defaultSortingOptionProvider: ~
        tags:
            - { name: gally.container_configuration.factory, requestType: generic, internal: true }

    gally.container_configuration.coverage_rate.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $aggregationProvider: '@Gally\Search\Elasticsearch\Request\Aggregation\Provider\CoverageAggregationProvider'
        tags:
            - { name: gally.container_configuration.factory, requestType: coverage_rate , internal: true }
                
    gally.container_configuration.autocomplete.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $aggregationProvider: '@Gally\Search\Elasticsearch\Request\Aggregation\Provider\AutocompleteSourceFields'
        tags:
            - { name: gally.container_configuration.factory, requestType: autocomplete }
                
    gally.container_configuration.category_count.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $aggregationProvider: '@Gally\Search\Elasticsearch\Request\Aggregation\Provider\CategoryCountAggregationProvider'
        tags:
            - { name: gally.container_configuration.factory, requestType: category_count , internal: true  }
