services:
    gally.container_configuration.product_catalog.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $defaultSortingOptionProvider: '@Gally\Product\Service\ProductDefaultSortingOptionProvider'
        tags:
            - { name: gally.container_configuration.factory, requestType: product_catalog, metadata: product }

    gally.container_configuration.product_search.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        tags:
            - { name: gally.container_configuration.factory, requestType: product_search, metadata: product }

    gally.container_configuration.product_autocomplete.factory:
        parent: 'Gally\Search\Elasticsearch\Request\Container\Configuration\GenericContainerConfigurationFactory'
        arguments:
            $aggregationProvider: '@Gally\Search\Elasticsearch\Request\Aggregation\Provider\AutocompleteSourceFields'
        tags:
            - { name: gally.container_configuration.factory, requestType: product_autocomplete, metadata: product }
