Gally\Category\Entity\Category\Configuration:
    properties:
        virtualRule:
            - Json: ~
        defaultSorting:
            - Gally\Product\Validator\DefaultSortingFieldConstraint: ~
