gally:
    graphql_query_renaming:
        Gally\Search\Model\Document:
            renamings:
                searchDocuments: documents
        Gally\Search\Model\Source\SortingOption:
            renamings:
                getSortingOptions: sortingOptions
    search_settings:
        aggregations:
            coverage_use_indexed_fields_property: false
        sort:
            default_asc_sort_field:
                - '_count'
                - '_score'
