gally:
    graphql_query_renaming:
        Gally\Search\Entity\Document:
            renamings:
                searchDocuments: documents
        Gally\Search\Entity\Source\SortingOption:
            renamings:
                getSortingOptions: sortingOptions
    autocomplete_settings:
        document_attribute:
            max_size: 3
    search_settings:
        default_date_field_format: 'yyyy'
        default_distance_unit: 'km'
        aggregations:
            coverage_use_indexed_fields_property: false
            default_date_range_interval: '1y'
            default_distance_ranges: 
                - {to: 1}
                - {from: 1, to: 5}
                - {from: 5, to: 10}
                - {from: 10, to: 20}
                - {from: 20, to: 30}
                - {from: 30, to: 50}
                - {from: 50, to: 100}
                - {from: 100, to: 200}
                - {from: 200}
        sort:
            default_desc_sort_field:
                - '_count'
                - '_score'
    request_types:
        - { code: product_catalog, label: 'Category listing', limitation_type: !php/const Gally\Search\Constant\RequestType\LimitationType::LIMITATION_CATEGORY }
        - { code: product_search, label: 'Search result', limitation_type: !php/const Gally\Search\Constant\RequestType\LimitationType::LIMITATION_SEARCH }
        - { code: product_autocomplete, label: 'Autocomplete', limitation_type: !php/const Gally\Search\Constant\RequestType\LimitationType::LIMITATION_SEARCH }
    pipeline_prefix: 'gally-llm-pipeline-'
    default_reference_location: 48.981299, 2.309959
