gally:
    graphql_query_renaming:
        Gally\Search\Model\Document:
            renamings:
                searchDocuments: documents
        Gally\Search\Model\Source\SortingOption:
            renamings:
                getSortingOptions: sortingOptions
    autocomplete_settings:
        document_attribute:
            max_size: 3
    search_settings:
        aggregations:
            coverage_use_indexed_fields_property: false
        sort:
            default_asc_sort_field:
                - '_count'
                - '_score'
    request_types:
        - { code: product_catalog, label: 'Category listing', limitation_type: !php/const Gally\Search\Constant\RequestType\LimitationType::LIMITATION_CATEGORY }
        - { code: product_search, label: 'Search result', limitation_type: !php/const Gally\Search\Constant\RequestType\LimitationType::LIMITATION_SEARCH }
