services:
    Gally\User\Repository\UserRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Gally\User\Repository\PasswordTokenRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
            
    Gally\User\DataFixtures\Providers\HashPasswordProvider:
        arguments:
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
        tags: 
          - { name: nelmio_alice.faker.provider }
    Gally\User\Service\UserManager:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\User\Repository\UserRepository'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            - '@Gally\Email\Service\EmailSender'
            - '@Gally\Configuration\Service\BaseUrlProvider'

    Gally\User\Service\Command\QuestionBuilder: ~

    Gally\User\Service\Command\Validation: 
        arguments:
            - '@Gally\User\Service\UserManager'
            - '@Symfony\Component\Validator\Validator\ValidatorInterface'

    Gally\User\Service\Command\Validator:
        arguments:
            - '@Gally\User\Service\Command\Validation'

    Gally\User\Command\CreateCommand:
        arguments:
            - '@Gally\User\Service\UserManager'
            - '@Gally\User\Service\Command\Validator'
            - '@Gally\User\Service\Command\QuestionBuilder'
        tags:
            - { name: console.command }
            
    Gally\User\Command\UpdateCommand:
        arguments:
            - '@Gally\User\Service\UserManager'
            - '@Gally\User\Service\Command\Validator'
            - '@Gally\User\Service\Command\QuestionBuilder'
        tags:
            - { name: console.command }
                
    Gally\User\EventSubscriber\ForgotPasswordEventSubscriber:
        arguments:
            - '@Gally\User\Service\UserManager'
            - '@request_stack'
        tags:
            - { name: kernel.event_subscriber }

    Gally\User\State\UserProcessor:
        arguments:
            - '@api_platform.doctrine.orm.state.persist_processor'
            - '@api_platform.doctrine.orm.state.remove_processor'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            - '@coop_tilleuls_forgot_password.manager.forgot_password'
            - '@coop_tilleuls_forgot_password.provider_chain'
        tags:
            - { name: api_platform.state_processor }
