gally:
    graphql_query_renaming:
        Gally\Product\Model\Product:
            renamings:
                searchProducts: products
                searchPreviewProducts: previewProducts
    autocomplete_settings:
        product_attribute:
            max_size: 3
    request_context:
        headers:
            - !php/const Gally\Entity\Service\PriceGroupProvider::PRICE_GROUP_ID

    default_price_group_id: 0
