gally:
    graphql_query_renaming:
        Gally\Product\Entity\Product:
            renamings:
                searchProducts: products
                searchPreviewProducts: previewProducts
    autocomplete_settings:
        product_attribute:
            max_size: 3
    request_context:
        headers:
            - !php/const Gally\Metadata\Service\PriceGroupProvider::PRICE_GROUP_ID
            - !php/const Gally\Metadata\Service\ReferenceLocationProvider::REFERENCE_LOCATION

    default_price_group_id: 0
