services:
    Gally\Job\Serializer\ImportFileNormalizer:
        arguments:
            - '@api_platform.jsonld.normalizer.item'
            - '@Vich\UploaderBundle\Storage\StorageInterface'
        tags:
            - { name: serializer.normalizer }

    Gally\Job\Repository\JobRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
                
    Gally\Job\Repository\Job\LogRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }
                
    Gally\Job\Repository\Job\ImportFileRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Gally\Job\MessageHandler\ProcessJobHandler:
        arguments:
            - '@Gally\Job\Service\JobManager'
        tags:
            - { name: messenger.message_handler,  handles: Gally\Job\Message\ProcessJob }

    Gally\Job\EventSubscriber\DispatchProcessJobMessage:
        arguments:
            - '@messenger.default_bus'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
                  
    Gally\Job\Service\JobManager:
        arguments:
            - '@doctrine.orm.entity_manager'
            - !tagged_iterator { tag: 'gally.job.export' }
            - !tagged_iterator { tag: 'gally.job.import' }
        
