services:
    Gally\Bundle\State\ExtraBundleProvider:
        arguments:
            - '@Symfony\Component\HttpKernel\KernelInterface'
        tags:
            - { name: api_platform.state_provider }
