Gally\Metadata\Entity\Metadata:
    properties:
        entity:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: entity
            
Gally\Metadata\Entity\SourceField:
    properties:
        code:
            - NotBlank: ~
        metadata:
            - NotBlank: ~
        type:
            - Choice: { callback: [Gally\Metadata\Entity\SourceField\Type, getAvailableTypes] }
        weight:
            - Choice: { callback: [Gally\Metadata\Entity\SourceField\Weight, getValidWeight] }
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ code, metadata ]
              message: 'A field with this code already exist for this entity.'
            
Gally\Metadata\Entity\SourceFieldLabel:
    properties:
        label:
            - NotBlank: ~
        sourceField:
            - NotBlank: ~
        localizedCatalog:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceField, localizedCatalog ]
              message: 'A label is already defined for this field and this localized catalog.'
            
Gally\Metadata\Entity\SourceFieldOption:
    properties:
        sourceField:
            - NotBlank: ~
        code:
            - NotBlank: ~
        defaultLabel:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceField, code ]
              message: 'An option with this code is already defined for this sourceField.'

Gally\Metadata\Entity\SourceFieldOptionLabel:
    properties:
        label:
            - NotBlank: ~
        sourceFieldOption:
            - NotBlank: ~
        localizedCatalog:
            - NotBlank: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ sourceFieldOption, localizedCatalog ]
              message: 'A label is already defined for this option and this localized catalog.'
