imports:
    - { resource: elasticsearch/request_type.yaml }

services:
    Gally\Tracker\State\TrackingEventProcessor:
        arguments:
            - '@messenger.default_bus'
        tags:
            - { name: api_platform.state_processor }
        
    Gally\Tracker\MessageHandler\TrackingEventHandler:
        arguments:
            - '@Gally\Index\Repository\DataStream\DataStreamRepositoryInterface'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - !tagged_iterator gally.tracker.validator
        tags:
            - { name: messenger.message_handler }

    Gally\Tracker\Validator\EventTypeValidator:
        tags:
            - { name: gally.tracker.validator }

    Gally\Tracker\Elasticsearch\Request\Aggregation\Provider\KpiAggregationProvider:
        arguments:
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'

    Gally\Tracker\State\KpiProvider:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\SimpleRequestBuilder'
            - '@Gally\Search\Elasticsearch\Request\Container\Configuration\ContainerConfigurationProvider'
            - '@Gally\Search\Elasticsearch\Adapter'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
        tags:
            - { name: api_platform.state_provider }
