imports:
    - { resource: attribute_factory.yaml }
services:
    Gally\Metadata\Repository\MetadataRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@ApiPlatform\Metadata\Resource\Factory\ResourceMetadataCollectionFactoryInterface'
            - '@Gally\ResourceMetadata\Service\ResourceMetadataManager'
        tags:
            - { name: doctrine.repository_service }

    Gally\Metadata\Repository\SourceFieldRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
        tags:
            - { name: doctrine.repository_service }

    Gally\Metadata\Repository\SourceFieldLabelRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Gally\Metadata\Repository\SourceFieldOptionRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Gally\Metadata\Repository\SourceFieldOptionLabelRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
        tags:
            - { name: doctrine.repository_service }

    Gally\Metadata\State\SourceFieldProcessor:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Catalog\Service\DefaultCatalogProvider'
            - '@Gally\Metadata\Repository\SourceFieldRepository'
            - '@Gally\Metadata\Repository\SourceFieldLabelRepository'
            - '@Gally\Metadata\Validator\SourceFieldDataValidator'
            - '@api_platform.doctrine.orm.state.remove_processor'
            - '%route_prefix%'
        tags:
            - { name: api_platform.state_processor }
 
    Gally\Metadata\State\SourceFieldOptionProcessor:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Metadata\Repository\SourceFieldRepository'
            - '@Gally\Metadata\Repository\SourceFieldOptionRepository'
            - '@Gally\Metadata\Repository\SourceFieldOptionLabelRepository'
            - '@Gally\Metadata\Validator\SourceFieldOptionDataValidator'
            - '@api_platform.doctrine.orm.state.remove_processor'
            - '%route_prefix%'
        tags:
            - { name: api_platform.state_processor }

    Gally\Metadata\EventSubscriber\ValidateSourceFieldCode:
        arguments:
            - '@Gally\Metadata\Repository\SourceFieldRepository'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Gally\Metadata\EventSubscriber\SpreadSourceFieldData:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Index\Service\MetadataManager'
            - '@Gally\Index\Service\IndexOperation'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '@logger'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    Gally\Metadata\EventSubscriber\GenerateSourceFieldSearch:
        arguments:
            - '@Gally\Metadata\Repository\SourceFieldRepository'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }

    Gally\Metadata\EventSubscriber\ValidateSourceFieldProperties:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Gally\Metadata\Controller\BulkSourceFields:
        arguments:
            - '@Gally\Metadata\State\SourceFieldProcessor'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Gally\Metadata\Controller\BulkSourceFieldOptions:
        arguments:
            - '@Gally\Metadata\State\SourceFieldOptionProcessor'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Gally\Metadata\Validator\SourceFieldDataValidator: 
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Gally\Metadata\Repository\MetadataRepository'
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '%route_prefix%'

    Gally\Metadata\Validator\SourceFieldOptionDataValidator: 
        arguments:
            - '@Gally\Catalog\Repository\LocalizedCatalogRepository'
            - '%route_prefix%'
                
    Gally\Metadata\GraphQl\Type\Definition\Filter\TextTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }
    
    Gally\Metadata\GraphQl\Type\Definition\Filter\BoolTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }
    
    Gally\Metadata\GraphQl\Type\Definition\Filter\IntegerTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }
    
    Gally\Metadata\GraphQl\Type\Definition\Filter\FloatTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }
    
    Gally\Metadata\GraphQl\Type\Definition\Filter\DateTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\GraphQl\Type\Definition\Filter\CategoryTypeDefaultFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\GraphQl\Type\Definition\Filter\PriceTypeDefaultFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '@Gally\Search\Service\SearchContext'
            - '@Gally\Search\Service\ReverseSourceFieldProvider'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\GraphQl\Type\Definition\Filter\SelectTypeDefaultFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\GraphQl\Type\Definition\Filter\StockTypeDefaultFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\GraphQl\Type\Definition\Filter\BoolFilterInputType:
        lazy: true
        arguments:
            - '@Gally\Product\GraphQl\Type\Definition\FieldFilterInputType'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
        tags:
            - { name: api_platform.graphql.type }
    
    Gally\Metadata\GraphQl\Type\Definition\Filter\LocationTypeFilterInputType:
        arguments:
            - '@Gally\Search\Elasticsearch\Builder\Request\Query\Filter\FilterQueryBuilder'
            - '@Gally\Search\Elasticsearch\Request\QueryFactory'
            - '@Gally\Search\GraphQl\Type\Definition\Filter\DistanceFilterInputType'
            - '%api_platform.graphql.nesting_separator%'
        tags:
            - { name: api_platform.graphql.type }
            - { name: gally.entity_api.filter }

    Gally\Metadata\Service\PriceGroupProvider:
        arguments:
            - '@Gally\RequestContext\Service\RequestContextManager'
            - '@Gally\Configuration\Service\ConfigurationManager'

    Gally\Metadata\Service\ReferenceLocationProvider:
        arguments:
            - '@Gally\RequestContext\Service\RequestContextManager'
            - '@Gally\Configuration\Service\ConfigurationManager'
