# /!\  File not loaded not loaded in the conf for the moment, kept only for the examples /!\
framework:
    cache:
          # system: default adapters are apcu and phpfiles and are chained together
          # in \Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension::registerCacheConfiguration:L.2124 
          
          # pools:
          # gally.example.simple.cache:
          #     adapter: cache.app
          
          # gally.example.tags.cache:
          #    adapter: cache.adapter.redis
        #    tags: true
