doctrine:
    dbal:
        types:
            jsonb: Gally\Doctrine\Type\JsonbType
        mapping_types:
            jsonb: jsonb
    orm:
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Postgresql\Date
            string_functions:
                STRING_AGG: DoctrineExtensions\Query\Postgresql\StringAgg
                ARRAY: Gally\Doctrine\Dql\ArrayFunction
                JSONB_EXISTS_ANY: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonbExistsAny
