doctrine:
    orm:
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Postgresql\Date
            string_functions:
                STRING_AGG: DoctrineExtensions\Query\Postgresql\StringAgg
