gally:
    configuration:
        scopes:
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LANGUAGE:
                labelKey: 'gally_configuration.scope.language.label'
                input: 'optgroup'
                options:
                    api_rest: '/language_options'
                    api_graphql: 'languageOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALE:
                labelKey: 'gally_configuration.scope.locales.label'
                input: 'optgroup'
                options:
                    api_rest: '/locale_group_options'
                    api_graphql: 'localeGroupOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_REQUEST_TYPE:
                labelKey: 'gally_configuration.scope.request_type.label'
                input: 'select'
                options:
                    api_rest: '/request_type_options'
                    api_graphql: 'requestTypeOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALIZED_CATALOG:
                labelKey: 'gally_configuration.scope.localized_catalog.label'
                input: 'optgroup'
                options:
                    api_rest: '/localized_catalog_group_options'
                    api_graphql: 'localizedCatalogGroupOptions'
                    
        groups:
            general:
                labelKey: 'gally_configuration.group.general.label'
                scopeType: !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALIZED_CATALOG               
                fieldsets:
                    general:
                        labelKey: 'gally_configuration.group.general.fieldset.general.label'
                        fields:
                            gally.base_url.media:
                                labelKey: 'gally_configuration.gally_base_url_media.label'
                                position: 10
                                input: 'string'
