gally:
    configuration:
        scopes:
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LANGUAGE:
                labelKey: 'gally_configuration.scope.languages.label'
                input: 'optgroup'
                filterName: 'language'
                options:
                    api_rest: '/configuration_language_options'
                    api_graphql: 'configurationLanguageOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALE:
                labelKey: 'gally_configuration.scope.locales.label'
                input: 'optgroup'
                filterName: 'localeCode'
                options:
                    api_rest: '/configuration_locale_group_options'
                    api_graphql: 'configurationLocaleGroupOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_REQUEST_TYPE:
                labelKey: 'gally_configuration.scope.request_type.label'
                input: 'select'
                filterName: 'requestType'
                options:
                    api_rest: '/configuration_request_type_options'
                    api_graphql: 'configurationRequestTypeOptions'
            !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALIZED_CATALOG:
                labelKey: 'gally_configuration.scope.localized_catalog.label'
                input: 'optgroup'
                filterName: 'localizedCatalogCode'
                options:
                    api_rest: '/configuration_localized_catalog_group_options?keyToGetOnValue=code'

        groups:
            general:
                labelKey: 'gally_configuration.group.general.label'
                scopeType: !php/const Gally\Configuration\Entity\Configuration::SCOPE_LOCALIZED_CATALOG 
                position: 10
                fieldsets:
                    general:
                        labelKey: 'gally_configuration.group.general.fieldset.general.label'
                        position: 10
                        fields:
                            gally.base_url.media:
                                labelKey: 'gally_configuration.gally_base_url_media.label'
                                position: 10
                                input: 'string'
                            gally.base_url.gally_front:
                                labelKey: 'gally_configuration.gally_base_url_gally_front.label'
                                position: 20
                                input: 'string'
