nelmio_cors:
    defaults:
        allow_headers:
            - !php/const Gally\Locale\EventSubscriber\LocaleSubscriber::GALLY_LANGUAGE_HEADER
            - !php/const Gally\Metadata\Service\PriceGroupProvider::PRICE_GROUP_ID
            - !php/const Gally\Metadata\Service\ReferenceLocationProvider::REFERENCE_LOCATION
