services:
    Gally\Analysis\Service\Config:
        public: true
        arguments:
            - '@Gally\Configuration\Service\ConfigurationManager'
            - '@Gally\Cache\Service\CacheManagerInterface'
